{application,project4,
             [{applications,[kernel,stdlib,elixir,logger,websocket_client,
                             poison,phoenix_gen_socket_client]},
              {description,"project4"},
              {modules,['Elixir.TwitterClone.Client',
                        'Elixir.TwitterClone.Main']},
              {registered,[]},
              {vsn,"0.1.0"},
              {extra_applications,[logger]}]}.
